[project]
name = "lo-remote-close"
version = "0.1.0"
description = "Tool for remotely closing Libreoffice documents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ooo-dev-tools>=0.53.3",
    "oooenv>=0.2.4",
]
